const imagesFolderPath = 'assets/';
const images = [
  '${imagesFolderPath}img_3.png',
  '${imagesFolderPath}img_12.png',
  '${imagesFolderPath}img_4.png',
  '${imagesFolderPath}img_1.png',
  '${imagesFolderPath}img_7.png',
  '${imagesFolderPath}img_11.png',
  '${imagesFolderPath}img_2.png',
  '${imagesFolderPath}img_9.png',
  '${imagesFolderPath}img_5.png',
  '${imagesFolderPath}img_8.png',
  '${imagesFolderPath}img_6.png',
  '${imagesFolderPath}img_10.png',
  '${imagesFolderPath}img_12.png',
  '${imagesFolderPath}img_6.png',
  '${imagesFolderPath}img_1.png',
  '${imagesFolderPath}img_7.png',
  '${imagesFolderPath}img_3.png',
  '${imagesFolderPath}img_11.png',
  '${imagesFolderPath}img_4.png',
  '${imagesFolderPath}img_8.png',
  '${imagesFolderPath}img_2.png',
  '${imagesFolderPath}img_9.png',
  '${imagesFolderPath}img_10.png',
  '${imagesFolderPath}img_5.png',
];